package application.enums

import kotlinx.serialization.Serializable
import server.serializers.IntEnumStatSerializer

@Serializable(with = IntEnumStatSerializer::class)
interface IntEnumStat

enum class EnumStatStock : IntEnumStat {
    // ========== STOCK - Основные характеристики ==========
    STOCK_HEALTH,
    STOCK_MANA,
    STOCK_ENERGY,
    STOCK_STRENGTH,
    STOCK_AGILITY,
    STOCK_INTELLECT,
    STOCK_CONSTITUTION,

    // ========== STOCK - Боевые характеристики ==========
    STOCK_ATTACK_PHYSICAL,
    STOCK_ATTACK_MAGICAL,
    STOCK_ATTACK_FIRE,
    STOCK_ATTACK_COLD,
    STOCK_ATTACK_LIGHTNING,
    STOCK_ATTACK_CHAOS,

    // ========== STOCK - Защита ==========
    STOCK_ARMOR,
    STOCK_EVASION,
    STOCK_ENERGY_SHIELD,
    STOCK_BLOCK_CHANCE,

    // ========== STOCK - Критические характеристики ==========
    STOCK_CRITICAL_CHANCE,
    STOCK_CRITICAL_DAMAGE,
    STOCK_CRITICAL_MULTIPLIER,
    STOCK_CRITICAL_VAMPIRE,

    // ========== STOCK - Скорость ==========
    STOCK_ATTACK_SPEED,
    STOCK_CAST_SPEED,
    STOCK_MOVEMENT_SPEED,

    // ========== STOCK - Сопротивления ==========
    STOCK_RESIST_FIRE,
    STOCK_RESIST_COLD,
    STOCK_RESIST_LIGHTNING,
    STOCK_RESIST_CHAOS,
    STOCK_RESIST_ALL,

    // ========== STOCK - Регенерация ==========
    STOCK_HEALTH_REGEN,
    STOCK_MANA_REGEN,
    STOCK_ENERGY_REGEN,
    STOCK_LEECH_PHYSICAL,
    STOCK_LEECH_MAGICAL,
    STOCK_LEECH_ALL,

    // ========== STOCK - Инвентарь и ресурсы ==========
    STOCK_INVENTORY_SIZE,
    STOCK_GOLD,
    STOCK_EXPERIENCE,

    // ========== STOCK - Особые статы ==========
    STOCK_RARITY,
    STOCK_QUANTITY,
    STOCK_STUN_THRESHOLD,
    STOCK_AURA_EFFECT,
    STOCK_CURSE_EFFECT,
    STOCK_CAST_STRENGTH,
}

enum class EnumStatBool : IntEnumStat {
    BOOL_ALIVE,
    BOOL_BANNED,
    BOOL_IN_COMBAT,
    BOOL_STUNNED,
    BOOL_FROZEN,
    BOOL_BURNING,
    BOOL_POISONED,
    BOOL_BLEEDING,
    BOOL_SHOCKED,
    BOOL_CHILLED,
    BOOL_CURSED,
    BOOL_INVISIBLE,
    BOOL_INVINCIBLE,
    BOOL_CONCENTRATING,
}

enum class EnumStatProfession : IntEnumStat {
    PROFESSION_LUMBERJACK,
    PROFESSION_STONEMASON,
    PROFESSION_ALCHEMY,
    PROFESSION_BLACKSMITH,
    PROFESSION_BUILDER,
    PROFESSION_TAILOR,
    PROFESSION_ENCHANTER,
    PROFESSION_JEWELER,
    PROFESSION_COOK,
    PROFESSION_FISHERMAN,
    PROFESSION_MINER,
    PROFESSION_FARMER,
    PROFESSION_HERBALIST,
    PROFESSION_CARPENTER,
    PROFESSION_CARTOGRAPHER,
    PROFESSION_HUNTER,
}

enum class EnumStatBattle : IntEnumStat {
    BATTLE_MELEE_COMBAT,
    BATTLE_SWORDSMANSHIP,
    BATTLE_AXE_COMBAT,
    BATTLE_POLEARM_COMBAT,
    BATTLE_UNARMED_COMBAT,
    BATTLE_DUAL_WIELDING,
    BATTLE_TWO_HANDED_WEAPON,
    BATTLE_RANGE_COMBAT,
    BATTLE_ARCHERY,
    BATTLE_CROSSBOW,
    BATTLE_THROWING,
    BATTLE_MAGIC_COMBAT,
    BATTLE_FIRE_MAGIC,
    BATTLE_WATER_MAGIC,
    BATTLE_EARTH_MAGIC,
    BATTLE_AIR_MAGIC,
    BATTLE_ELECTRIC_MAGIC,
    BATTLE_DARK_MAGIC,
    BATTLE_LIGHT_MAGIC,
    BATTLE_CHAOS_MAGIC,
    BATTLE_SUMMONING,
}